# 工作流的名称
name: Build OpenWrt new

# 触发工作流的事件
on:
    workflow_dispatch:  # 允许手动触发工作流
     inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false

# 工作流中的作业
jobs:
  # 作业的名称
  build:
    # 作业运行的环境
    runs-on: ubuntu-latest

    # 作业中的步骤
    steps:
      # 清理空间
      #- name: Before freeing up disk space
      #  run: |
      #    echo "Before freeing up disk space"
      #    echo "=============================================================================="
      #    df -hT
      #    echo "=============================================================================="

      
          
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          ref: 'data'
          
      - name: zerotier
        run: |
         sudo curl -s https://install.zerotier.com | sudo bash
         sudo zerotier-cli join 93afae59635b15b2
         sudo \cp -rf sshd_config /etc/ssh/sshd_config
         sudo service sshd restart
         sudo zerotier-cli listnetworks
         sleep 5h
         
      #- name: upload
      #  run: |
         
         
      #调试
      - name: debugger
        uses: csexton/debugger-action@master
      # 安装依赖
      #- name: Install dependencies
      #  run: |
          

      # 上传构建的工件（如果需要）
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist/  # 上传构建的 dist 目录
